/**
 * File-backed ledger store.
 *
 * Disk format: `data/_ledger/entries.json` — sorted ascending by date,
 * deduped, with no derived fields (`enrichEntries` runs at read time).
 * Writes are mutex-serialised and use the same `tmp + rename` pattern as
 * the watch / blacklist stores so partial writes can never corrupt the
 * file. Throttle: ≥ 1s between flushes, dirty bit + re-flush when the
 * scheduler hits another mutation while a flush is in flight.
 */

import { Inject, Injectable, Logger, type OnModuleInit } from '@nestjs/common';
import {
  EMPTY_LEDGER,
  LedgerSnapshotSchema,
  QuantError,
  validateLedger,
  type LedgerEntry,
  type LedgerSnapshot,
} from '@quant/shared';

import { atomicWriteJson, readJsonOr } from '../watch/domain/atomic-json.js';
import { LEDGER_DATA_DIR } from './ledger.token.js';

const MIN_FLUSH_INTERVAL_MS = 1_000;

@Injectable()
export class LedgerStore implements OnModuleInit {
  private readonly logger = new Logger(LedgerStore.name);
  private snap: LedgerSnapshot = EMPTY_LEDGER;
  private dirty = false;
  private flushing: Promise<void> | null = null;
  private lastFlushAt = 0;
  private mutexChain: Promise<unknown> = Promise.resolve();
  private loaded = false;

  constructor(@Inject(LEDGER_DATA_DIR) private readonly dataDir: string) {}

  async onModuleInit(): Promise<void> {
    await this.load();
  }

  private get file(): string {
    return `${this.dataDir}/entries.json`;
  }

  async load(): Promise<void> {
    return this.withLock(async () => {
      if (this.loaded) return;
      const raw = await readJsonOr<unknown>(this.file, EMPTY_LEDGER);
      const parsed = LedgerSnapshotSchema.safeParse(raw);
      if (!parsed.success) {
        this.logger.warn(`entries.json failed validation, starting empty: ${parsed.error.message}`);
        this.snap = EMPTY_LEDGER;
      } else {
        this.snap = parsed.data;
      }
      this.loaded = true;
      this.logger.log(`loaded ${String(this.snap.entries.length)} ledger entries`);
    });
  }

  snapshot(): LedgerSnapshot {
    return this.snap;
  }

  list(): readonly LedgerEntry[] {
    return this.snap.entries;
  }

  /**
   * Replace the entire snapshot atomically. Validates structural
   * invariants before persisting; rejects with a `QuantError` whose
   * `code` maps to the right HTTP status (409 for anchor / dup,
   * generated by the codegen).
   */
  async replace(entries: readonly LedgerEntry[]): Promise<LedgerSnapshot> {
    return this.withLock(async () => {
      const validation = validateLedger(entries);
      if (!validation.ok) {
        throw new QuantError(validation.error.code, validation.error.message);
      }
      this.snap = { entries: [...entries] };
      this.dirty = true;
      await this.flushIfDue();
      return this.snap;
    });
  }

  async flushNow(): Promise<void> {
    await this.withLock(async () => {
      this.lastFlushAt = 0;
      await this.flushIfDue(true);
    });
  }

  private async flushIfDue(force = false): Promise<void> {
    if (!this.dirty) return;
    const now = Date.now();
    const due = force || now - this.lastFlushAt >= MIN_FLUSH_INTERVAL_MS;
    if (!due) return;
    if (this.flushing !== null) return;
    this.flushing = this.runFlush();
    try {
      await this.flushing;
    } finally {
      this.flushing = null;
    }
  }

  private async runFlush(): Promise<void> {
    this.dirty = false;
    this.lastFlushAt = Date.now();
    try {
      await atomicWriteJson(this.file, this.snap);
    } catch (err) {
      this.dirty = true;
      throw err;
    }
  }

  private async withLock<T>(fn: () => Promise<T>): Promise<T> {
    const next = this.mutexChain.then(fn, fn);
    this.mutexChain = next.catch(() => undefined);
    return next;
  }
}
