/**
 * DDE 主力 fund-flow sync (modules/01-stock-meta.md §5).
 *
 * One per-batch tick:
 *   1. Pull the per-window full-market 主力净流入 ranks via the Python
 *      `list_stock_fund_flow_ranks` Flight op (1 call → 4 windows on
 *      the wire, joined Arrow table back).
 *   2. Aggregate the local kline `amount` column over the trailing N
 *      trade dates per code via DuckDB (one GROUP BY, all 4 windows in
 *      a single CASE WHEN).
 *   3. Divide → ratio (Decimal, 6 dp); null when the local kline window
 *      has < N bars or sums to zero. The raw net-inflow column lands
 *      regardless so consumers can rebuild any other denominator
 *      without a re-fetch.
 *   4. Hand the merged rows to {@link LocalStockMetaWriterService#upsertFundFlow}.
 *
 * Settle ordering: kicked off by `BatchSettler` after the per-code
 * kline sync finishes (so amount sums hit the freshly-written rows)
 * and after blacklist recompute (so a code added to the blacklist
 * mid-batch doesn't get a partial DDE row). Failures are warned-and-
 * skipped — yesterday's row stays on disk and the next cron tick
 * retries.
 */

import { join } from 'node:path';
import { Inject, Injectable, Logger } from '@nestjs/common';
import type { DuckDBConnection } from '@duckdb/node-api';
import { DuckDBInstance } from '@duckdb/node-api';
import { DDE_WINDOWS, QuantError, type DdeWindow } from '@quant/shared';
import { Decimal } from 'decimal.js';

import { FlightClient } from '../../adapters/flight/flight-client.js';
import { KLINE_DATA_DIR } from '../kline/kline.token.js';
import { arrowTableToFundFlowRanks } from './domain/fund-flow-arrow-mapper.js';
import {
  LocalStockMetaWriterService,
  type StockFundFlowRow,
} from './local-stock-meta-writer.service.js';

export const STOCK_FUND_FLOW_FLIGHT_CLIENT = Symbol('STOCK_FUND_FLOW_FLIGHT_CLIENT');

const RATIO_DP = 6;

interface AmountByWindow {
  /** Trailing-N-day amount sum, or null when the local kline has < N bars. */
  readonly byWindow: ReadonlyMap<DdeWindow, Decimal | null>;
}

@Injectable()
export class StockFundFlowSyncService {
  private readonly logger = new Logger(StockFundFlowSyncService.name);
  private readonly klineGlob: string;
  private connPromise: Promise<DuckDBConnection> | null = null;

  constructor(
    @Inject(STOCK_FUND_FLOW_FLIGHT_CLIENT) private readonly flight: FlightClient,
    @Inject(LocalStockMetaWriterService)
    private readonly writer: LocalStockMetaWriterService,
    @Inject(KLINE_DATA_DIR) klineDataRoot: string,
  ) {
    // The kline LSM store writes `<dataRoot>/kline/<prefix>.parquet`.
    // The glob covers every prefix in a single DuckDB scan — adding
    // new prefixes (300 / 301 / 600 / ...) requires no code change.
    this.klineGlob = join(klineDataRoot, 'kline', '*.parquet');
  }

  /**
   * Run a full DDE sync over the universe.
   *
   * @param traceId  forwarded onto the Flight call for cross-process
   *                 correlation; one is generated by the FlightClient
   *                 when omitted (we only need it explicit when the
   *                 caller is propagating a batch-level trace).
   */
  async syncAll(traceId?: string): Promise<{ written: number; ranked: number }> {
    const result = await this.flight.doGet(
      'list_stock_fund_flow_ranks',
      {},
      traceId === undefined ? {} : { traceId },
    );
    const ranks = arrowTableToFundFlowRanks(result.value);
    if (ranks.length === 0) {
      this.logger.warn('fund_flow_sync_empty_rank — skipping upsert');
      return { written: 0, ranked: 0 };
    }
    const amountByCode = await this.loadAmountSums();
    const rows = this.buildRows(ranks, amountByCode);
    await this.writer.upsertFundFlow(rows);
    this.logger.log(
      `fund_flow_sync_done ranked=${String(ranks.length)} written=${String(rows.length)}`,
    );
    return { written: rows.length, ranked: ranks.length };
  }

  private buildRows(
    ranks: readonly { code: string; mainNetInflowByWindow: ReadonlyMap<DdeWindow, string | null> }[],
    amountByCode: ReadonlyMap<string, AmountByWindow>,
  ): StockFundFlowRow[] {
    const out: StockFundFlowRow[] = [];
    for (const rank of ranks) {
      const amount = amountByCode.get(rank.code);
      const row: Record<string, string | null> = { code: rank.code };
      for (const w of DDE_WINDOWS) {
        const inflowStr = rank.mainNetInflowByWindow.get(w) ?? null;
        row[`dde_main_net_inflow_${w}d`] = inflowStr;
        row[`dde_main_inflow_ratio_${w}d`] = computeRatio(
          inflowStr,
          amount?.byWindow.get(w) ?? null,
        );
      }
      out.push(row as unknown as StockFundFlowRow);
    }
    return out;
  }

  private async loadAmountSums(): Promise<ReadonlyMap<string, AmountByWindow>> {
    const conn = await this.connection();
    // ROW_NUMBER per code DESC by ts; the per-window sums use CASE WHEN
    // gates so the whole universe is computed in a single GROUP BY.
    // `bar_count` lets us null out windows shorter than N bars.
    const windowSumExprs = DDE_WINDOWS.map((w) => {
      const n = String(w);
      return `SUM(CASE WHEN rn <= ${n} THEN amount END) AS amt_${n}d`;
    }).join(',\n        ');
    const sql = `
      WITH ranked AS (
        SELECT code, amount,
               ROW_NUMBER() OVER (PARTITION BY code ORDER BY ts DESC) AS rn
        FROM read_parquet(${quoteLiteral(this.klineGlob)})
      )
      SELECT code,
        COUNT(*) AS bar_count,
        ${windowSumExprs}
      FROM ranked
      GROUP BY code
    `;
    let result;
    try {
      result = await conn.runAndReadAll(sql);
    } catch (err) {
      // Empty data dir → no parquet files matched. Treat as "no kline
      // available" rather than aborting the whole DDE sync.
      const msg = err instanceof Error ? err.message : String(err);
      if (/no files found/i.test(msg) || /IO Error/i.test(msg)) {
        this.logger.warn(`fund_flow_sync_kline_unavailable msg=${msg}`);
        return new Map();
      }
      throw new QuantError('INTERNAL', `kline-amount aggregation failed: ${msg}`);
    }
    const rows = result.getRowObjects();
    const out = new Map<string, AmountByWindow>();
    for (const raw of rows) {
      const row = raw as Record<string, unknown>;
      const code = row['code'];
      if (typeof code !== 'string') continue;
      const barCount = numberFromRow(row['bar_count']);
      const byWindow = new Map<DdeWindow, Decimal | null>();
      for (const w of DDE_WINDOWS) {
        if (barCount === null || barCount < w) {
          byWindow.set(w, null);
          continue;
        }
        const colName = `amt_${String(w)}d`;
        const sum = numberFromRow(row[colName]);
        byWindow.set(w, sum === null ? null : new Decimal(sum));
      }
      out.set(code, { byWindow });
    }
    return out;
  }

  private connection(): Promise<DuckDBConnection> {
    this.connPromise ??= (async (): Promise<DuckDBConnection> => {
      const inst = await DuckDBInstance.create(':memory:');
      return inst.connect();
    })();
    return this.connPromise;
  }
}

export function computeRatio(
  inflowStr: string | null,
  amountSum: Decimal | null,
): string | null {
  if (inflowStr === null || amountSum === null || amountSum.isZero()) {
    return null;
  }
  // `inflowStr` arrived from akshare-as-string; `new Decimal(...)` will
  // throw on a malformed value, surfacing a server-side parse failure
  // rather than silently emitting a bogus ratio.
  return new Decimal(inflowStr)
    .div(amountSum)
    .toDecimalPlaces(RATIO_DP, Decimal.ROUND_HALF_EVEN)
    .toString();
}

function numberFromRow(value: unknown): number | null {
  if (value === null || value === undefined) return null;
  if (typeof value === 'number') return Number.isFinite(value) ? value : null;
  if (typeof value === 'bigint') return Number(value);
  if (typeof value === 'string') {
    const n = Number(value);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

function quoteLiteral(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}
